MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.025
    DA_INS_GRL_WEIGHT: 0.1
    COS_WEIGHT: 0.1
  MIC_ON: True
  MASKING_AUGMENTATION: True
  PSEUDO_LABEL_THRESHOLD: 0.8
  PSEUDO_LABEL_LAMBDA: 1.0
  PSEUDO_LABEL_WEIGHT: 'prob'
  MASKING_BLOCK_SIZE: 32
  MASKING_RATIO: 0.5
  TEACHER_ALPHA: 0.9
DATASETS:
  SOURCE_TRAIN: ("my_org_train",)
  TARGET_TRAIN: ("my_fog_train",)
  TEST: ("",)
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 40000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
